# **USEFUL LINKS**

In [ ]:
Links with more information! 

NumPy vs Lists:
https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

Indexing: 
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

Array Creation Routines:
https://numpy.org/doc/stable/reference/routines.array-creation.html

Math Routines Docs:
https://numpy.org/doc/stable/reference/routines.math.html

Linear Algebra Docs:
https://numpy.org/doc/stable/reference/routines.linalg.html


# **MATHEMATICS**

In [41]:
import numpy as np 

In [42]:
a = np.array([1,2,3,4])
print (a)

[1 2 3 4]


# **Subtraction**

In [43]:
a - 2 

array([-1,  0,  1,  2])

# **Addition**

In [44]:
#a + 2
# can also do by this way
a +=2
a

array([3, 4, 5, 6])

# **Multiplication**

In [45]:
a * 2 

array([ 6,  8, 10, 12])

# **Division**

In [46]:
a / 2 

array([1.5, 2. , 2.5, 3. ])

In [47]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [48]:
a **2 

array([ 9, 16, 25, 36])

In [49]:
# Take the sin of all the values
# Formula = np.sin/cos/tan(variable of your choice ) and also function of your choice 
# Formula = 
np.cos(a)


array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [50]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

# **LINEAR ALGEBRA**

In [51]:
import numpy as np

# ============================================================
# LINEAR ALGEBRA IN NUMPY
# ============================================================
# Linear Algebra is the mathematics of vectors and matrices.
# It is the backbone of Machine Learning and Deep Learning.
# Every single ML operation at its core is linear algebra.
#
# WHY IT IS IMPORTANT IN ML:
# Neural Network forward pass  → X @ W + b
# PCA                          → eigenvalues and eigenvectors
# Solving optimization         → np.linalg.solve
# Measuring similarity         → dot product
# Image transformations        → matrix multiplication
#
# WITHOUT LINEAR ALGEBRA THERE IS NO ML. PERIOD.
#
# NumPy makes linear algebra:
# → Fast    (runs in C under the hood)
# → Simple  (one line instead of 50 lines)
# → Accurate (no manual calculation errors)
# ============================================================

# ============================================================
# MATRIX MULTIPLICATION RULES (Keith Galli)
# ============================================================
# RULE: columns of FIRST matrix must match rows of SECOND matrix
#
# A.shape = (2,3) → 2 rows, 3 columns
# B.shape = (3,2) → 3 rows, 2 columns
#
# columns of A = 3 ✅ matches rows of B = 3
# if they dont match → ERROR
#
# Result shape = (rows of A, columns of B)
# Result shape = (2,2)
# ============================================================

a = np.ones((2,3))
print(a)
# [[1. 1. 1.]
#  [1. 1. 1.]]

b = np.full((3,2),2)
print(b)
# [[2 2]
#  [2 2]
#  [2 2]]

# Matrix Multiplication
# Formula = np.matmul(first array, second array)
# OR use @ operator → a @ b (exact same thing, cleaner)
result = np.matmul(a,b)
print(result)
# [[6. 6.]
#  [6. 6.]]

# WHY 6?
# each element = sum of (row of A multiplied by column of B)
# row of A    = [1, 1, 1]
# column of B = [2, 2, 2]
# (1x2) + (1x2) + (1x2) = 2 + 2 + 2 = 6
#
# This exact operation X @ W is what every
# dense layer in a neural network does
# X = input data
# W = weights
# result = predictions

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [52]:
a = np.ones((2,3))
print(a)

b = np.full((3,2 ),2)
print (b)
# To Multiply the two array in linear algebra 
# We use matmul (Matrix Multiplication) to multiply the matrix
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [53]:
# Find the Determinant 
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)