# **INITIALIZING DIFFFERENT TYPES OF ARRAYS (P2)**

In [1]:
import numpy as np 

In [5]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [2]:
# All Zeros Matrix
np.zeros((2,4,6))


array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [3]:
# All ones Matrix
np.ones((3,2,1,6))

array([[[[1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.]]]])

In [4]:
# Any other number 
np.full((2,3,2),44)

array([[[44, 44],
        [44, 44],
        [44, 44]],

       [[44, 44],
        [44, 44],
        [44, 44]]])

In [8]:
# Any other Number (full-like)
# Formula = agar ap kay pass koi purani array hai to ap us ko change kar saktaye ho
# ye pori array ko badal dayate hain 
# Real Formula = np.full_like(write the name of array,and your no.)
np.full_like(a,4)
# we can also do that 
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

# **RANDOM DECIMAL NUMBERS**

In [12]:
np.random.rand(2,3,5)  # work in this way (BLOCK,SLICE,ROW,COLUMN)
# np.random.rand(2,3,5) generates a 3D array
# shape (2 slices, 3 rows, 5 columns)
# filled with random floats between 0 and 1
 

array([[[0.0114415 , 0.50412359, 0.6066973 , 0.73176904, 0.10063231],
        [0.87571588, 0.09769844, 0.60242883, 0.4214172 , 0.43005358],
        [0.63223465, 0.65215603, 0.62344826, 0.88222594, 0.07440172]],

       [[0.15723716, 0.50640355, 0.57523983, 0.97815387, 0.74828313],
        [0.54024296, 0.86156625, 0.33169925, 0.97364092, 0.15882696],
        [0.74694807, 0.34129623, 0.35632977, 0.16772274, 0.09165395]]])

In [13]:
# You can also do that by little bit changing the formula 
# Formula = np.random.random_sample(write the previous varibale.shape)
np.random.random_sample(a.shape)

array([[0.75790989, 0.29243609, 0.39969885, 0.04661571, 0.59040301,
        0.44158723, 0.01388128, 0.61455329, 0.00627343, 0.21875106],
       [0.15241774, 0.32205162, 0.34074628, 0.33210311, 0.68033965,
        0.57166705, 0.54610758, 0.75833612, 0.11426954, 0.54647544]])

# **RANDOM INTEGER VALUES**

In [77]:
np.random.randint(-2,8,size=(3,3))
#Explanation = The command np.random.randint(7, size=(3,3)) 
#generates a 3x3 matrix (2-dimensional array) populated with random integers
#ranging from 0 to 6 (inclusive).

array([[-1, -1, -1],
       [ 1, -1,  0],
       [-2,  0,  1]], dtype=int32)

# **THE IDENTITY MATRIX**

In [78]:
# THE IDENTITY MATRIX 
# formula = np.identity(no. of your choice)
# EXPLANATION : gernerates a square of the no. you wrote for example 5 the diagonals will be 1s and all other will be zeros
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# **Repeat an Array**

In [82]:
s = np.array([[1,2,3]])
r1  = np.repeat(s,3,axis=0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# **PROBLEM**

In [99]:
import numpy as np

# Create a 5x5 array filled with all 1s
# This is our main output array (the big one)
output = np.ones((5,5))
print(output)
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]

# Create a 3x3 array filled with all 0s
# This is our smaller array that we will paste inside output
z = np.zeros((3,3))

# Put 9 in the middle of z
# z has rows 0,1,2 and columns 0,1,2
# middle is row 1, column 1
z[1,1] = 9
print(z)
# [[0. 0. 0.]
#  [0. 9. 0.]
#  [0. 0. 0.]]

# We want to paste z (3x3) into the middle of output (5x5)
# output has 5 rows (0,1,2,3,4) and 5 columns (0,1,2,3,4)
# we want to skip the border (first and last row/column)
# so we only touch rows 1,2,3 and columns 1,2,3

# 1:-1 breakdown:
# 1    = start from index 1 (skip row/column 0 which is the border)
# -1   = stop before the last index (skip row/column 4 which is the border)
# so 1:-1 gives us indices 1, 2, 3 (the middle part)

#        ROWS  | COLUMNS
output[1:-1,    1:-1] = z
# this line is saying:
# go into output
# select rows 1,2,3 (skip first row 0 and last row 4)
# select columns 1,2,3 (skip first column 0 and last column 4)
# that selected middle area is exactly 3x3
# now paste z into that 3x3 middle area
# = z means fill that selected area with whatever z contains

print(output)
# [[1. 1. 1. 1. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 0. 9. 0. 1.]
#  [1. 0. 0. 0. 1.]
#  [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# **BE CAREFUL WHEN COPYING ARRAYS**

In [110]:
# Why .copy() function is so important 
# Without using the .copy function this happens
y = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b = y 
b[1,:] = 100
print (b)
# But then if you print a the original elements will be replaced 
print (y)

[[  1   2   3   4   5   6   7   8   9  10]
 [100 100 100 100 100 100 100 100 100 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [100 100 100 100 100 100 100 100 100 100]]


In [116]:
# Why .copy() function is so important 
#  using the .copy function this happens
y = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b = y.copy() 
b[1,:] = 100
print(b)
# But then if you print  the original elements will not  be replaced 
print (y) 

[[[  1   2   3]
  [  4   5   6]]

 [[100 100 100]
  [100 100 100]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
