# **AGGREGATE FUNCTIONS = SUMMARIZE DATA AND TYPICALLY RETURNS A SINGLE VALUE**

In [17]:
import numpy as np 

In [18]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10],
                [11,12,13,14,15,16,17,18,19,20]])
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [38]:
# ALL BASIC AGGREGATE FUNCTIONS 
print(np.sum(arr,axis=0)) # with axis you can define how it will do the operation with axis=0 it will do column wise 
print(np.sum(arr,axis=1)) # with axis you can define how it will do the operation with axis=1 it will do row wise 

print(np.mean(arr))

print(np.median(arr))

# For STANDARD DERIVATION
print(np.std(arr))

# For VARIENCE
print(np.var(arr))

print(np.min(arr))

print(np.max(arr))

print(np.argmin(arr))




[12 14 16 18 20 22 24 26 28 30]
[ 55 155]
10.5
10.5
5.766281297335398
33.25
1
20
0


In [20]:
arr_0 = np.array([[1,2,3,4,5,6,7,8,9,10],
                [11,12,13,14,15,16,17,18,19,20]])

# **ELEMENT-WISE MATH**

In [21]:
# ye functions har ek element pe individually kaam karte hain
# poori array ek saath process hoti hai — koi loop nahi


# Square root — har element ka square root nikalta hai
print(np.sqrt(arr_0))

[[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]]


In [22]:
print(np.exp(arr_0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03 2.20264658e+04]
 [5.98741417e+04 1.62754791e+05 4.42413392e+05 1.20260428e+06
  3.26901737e+06 8.88611052e+06 2.41549528e+07 6.56599691e+07
  1.78482301e+08 4.85165195e+08]]


In [23]:
print(np.log(arr_0))

[[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
  1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502  2.77258872
  2.83321334 2.89037176 2.94443898 2.99573227]]


# **AXIS PARAMETER**

In [24]:
# axis=0 → ROWS collapse karo → column wise operation
# axis=1 → COLUMNS collapse karo → row wise operation
# Visualization:
# arr = [[1,  2,  3,  4,  5,  6,  7,  8,  9,  10],   ← row 0
#        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]    ← row 1
#          ↓   ↓   ↓   ↓   ↓   ↓   ↓   ↓   ↓   ↓
#        col0 col1 col2 ...                col9
print(np.sum(arr_0,axis=0))

[12 14 16 18 20 22 24 26 28 30]


In [25]:
# axis=1 → add karo left right (columns collapse)
# row0: 1+2+3+...+10=55, row1: 11+12+...+20=155
print(np.sum(arr_0, axis=1))

[ 55 155]


In [35]:
# Same concept for mean
print(np.mean(arr_0,axis=0))
print(np.mean(arr_0,axis=1))

[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 5.5 15.5]


# **ARGMIN AND ARGMAX WITH AXIS**

In [33]:
# argmin/argmax → value nahi INDEX return karta hai
# without axis → flat index deta hai (poori array ek line mein)
# with axis    → index per row ya per column deta hai
print(np.min(arr_0)) # it goes vertically like 1,11 so it is 0

1


In [39]:
print(np.argmax(arr_0,axis=1))# it goes side ways or horizontally from first element of row to its 

[9 9]


In [40]:
# 
# FROM SCRATCH — MEAN
# 
# Mean ki working = np.mean() andar yahi karta hai
# Formula: sab elements ka total / kitne elements hain

def my_mean(arr_0):
    return np.sum(arr_0) / arr_0.size
    # np.sum(arr_0) → sab elements ko add karo → 210
    # arr_0.size    → total elements kitne hain → 20
    # 210 / 20      → 10.5

print(my_mean(arr))  # 10.5
print(np.mean(arr))  # 10.5 → same → proved ✅
# Matlab my_mean() exactly np.mean() ki working hai

#
# FROM SCRATCH — MIN
#
# Min ki working = np.min() andar yahi karta hai
# Logic: sab elements se compare karo, sabse chhota dhundho

def my_min(arr_0):
    result = arr_0.flat[0]
    # pehle element ko sabse chhota maan lo → result = 1

    for x in arr_0.flat:
        # x = ek ek element → 1,2,3,4...20
        if x < result:
            # kya ye element result se chhota hai?
            result = x
            # haan → result update karo

    return result
    # sabse chhota element return karo

print(my_min(arr))  # 1
print(np.min(arr))  # 1 → same → proved ✅
# Matlab my_min() exactly np.min() ki working hai


10.5
10.5
1
1
