# ACCESSING AND CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS ETC...

In [5]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [9]:
# Get a sepcific element [r, c] 
#Formula = variable[specify row,specify column]
# For example 
int(a[1, 4])

15

## Get a Specific Row 

In [13]:
# Formula = variable[specify row no., :]
a[0,:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Get Specific Column

In [14]:
# Formula = varible[:, specify column]
a[:,5]

array([ 6, 16])

In [28]:
# Get a little  more fancy
# Formula= variable[sepcify row,startindex:endindex:setpsize]
# Tip: Like range fucn in Python in it excludes the last one so in this 
# function it excludes the first start index like if you wirte form 1st 
# element so it will begin from 2nd element and if you said from 0 
# so then it will begin from 1st element 
a[0,1:10:2]

array([ 2,  4,  6,  8, 10])

In [26]:
a[1,0:10:2]
# Explanation of the above code 
# a is a variable that has a 2d array the first 1 in the code [1,] is 
# specifying the row of the array in variable a [1,0] here 0 is sepcifying
# the start of this function it exludes the one you write if you tell it to 
# start from 1 then it will start from 2nd element [1,0:10:2] 10 is
# representing the last element and this will include it :2 is specifying 
# the step size 

array([11, 13, 15, 17, 19])

# CHANGING FUNCTIONS 

In [31]:
# Changing the Value of an element 
# Formula = variable[tell its row,column]= write the vlaue you wanted 
a[1,4]=100
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14 100  16  17  18  19  20]]


In [38]:
# IF you want the same thing as above for a series of numbers 
# Formula = varible[specify the row or column]= then the element you want 
a[:,9]= [15,30]
print (a)

[[  1   2   3   4   5  10   7   8   9  15]
 [ 11  12  13  14 100  10  17  18  19  30]]


# From 3D ARRAY EXAMPLE 

In [6]:
b = np.array([
    [           # slice 0  
        [1,2],  # row 0
        [3,4]   # row 1 
    ],
    [          # slice 1 
        [5,6], # row 0
        [7,8]  # row 1 
    ]
])
print (b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# Get Specific Element  (work by [slice,row,column])
# Formula / Explanation = b[SLICE, ROW,COLUMN]
int(b[1,0,1])

6

In [17]:
# if you want to replace it with any other value in 3d array 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# **Initializing different types of Arrays**

In [25]:
# All 0s matrix
np.zeros((2,2,4))
# Explanation is that first 2 define slices, 2 defines no.of rows and 
# and last 4 defines no.of columns

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
# All ones matrix
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# Any Other Number 
np.full((4,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
Links with more information! 

NumPy vs Lists:
https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

Indexing: 
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

Array Creation Routines:
https://numpy.org/doc/stable/reference/routines.array-creation.html

Math Routines Docs:
https://numpy.org/doc/stable/reference/routines.math.html

Linear Algebra Docs:
https://numpy.org/doc/stable/reference/routines.linalg.html