# **ALL MISSING TASKS HERE**

In [2]:
import numpy as np

# **Arrays with PreDefault Vlaues**

In [29]:
# like an array with any number you want in this e.g we take 7
a = np.full((2,3,4),7)
print (a)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


# **DEFAULT VALUES FUNCTIONS**

In [30]:
b = np.zeros((2,3))
print (b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
c = np.ones((2,2,2,5))
print (c)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


# **EMPTY FUNCTION**

In [32]:
# Explanation 
# np.empty()
# Ek NumPy function jo ek array banata hai bina uske values initialize
# kiye — sirf memory allocate karta hai.
# Jo bhi pehle se us memory mein garbage values hoti hain, wahi dikhta hai 
# — isliye ye fastest array creation method hai.
# Example: np.empty((3,3)) likh do — tumhe ek 3x3 array milega random
# garbage numbers ke saath, koi zeros ya ones nahi.
d = np.empty((5,3,2))

print (d)

[[[1.11179473e-311 1.11171240e-311]
  [0.00000000e+000 0.00000000e+000]
  [6.63446432e+246 5.02034658e+175]]

 [[3.70244319e-033 6.23882825e-042]
  [2.25578626e+180 5.49842733e+170]
  [2.76749938e-057 4.01458717e-057]]

 [[3.83819517e+151 2.59903818e-144]
  [1.04918562e-153 7.69165785e+218]
  [5.04621343e+180 1.04917822e-153]]

 [[9.08366793e+223 3.70244319e-033]
  [6.23882825e-042 2.25578626e+180]
  [5.49842733e+170 1.04914965e-153]]

 [[1.94918966e-153 3.93231563e-062]
  [9.71376846e-067 3.89487766e-033]
  [2.59027896e-144 7.79952704e-143]]]


# **ARANGE FUNCTION**

In [35]:
# np.arange()
# Ek NumPy function jo ek sequence of numbers banata hai — exactly jaise Python
# ka range(), but output ek array hota hai.
# Tum start, stop, aur step define karte ho — aur ye us range mein evenly
# spaced values generate karta hai.
# Example: np.arange(0, 10, 2) dega [0, 2, 4, 6, 8] — 0 se shuru, 10 se
# pehle ruko, har baar 2 ka jump.
# Formula = np.arange(Start value , Stop Vlaue (Excluded), Stepsize)
x_values = np.arange(0,105,5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


# **NP.LINSPACE**

In [9]:
# np.linspace()
# Ek NumPy function jo do numbers ke beech mein exactly N evenly spaced values banata hai.
# np.arange() se fark ye hai ke tum step nahi, balki total kitne points
# chahiye wo batate ho — aur ye khud calculate karta hai spacing.
# Example: np.linspace(0, 1, 5) dega [0.0, 0.25, 0.5, 0.75, 1.0] 
# — 0 se 1 tak, exactly 5 points, equal gap ke saath.
# Formula = np.linspace(Start Value, Stop value, and the number you want to be in half by this func)
x_values_0 = np.linspace(0,100,3)
print (x_values_0)
x_values_1 = np.linspace(0,100,4,endpoint=False) # if you say endpoint=false it will not include the last value as it does defaulty
x_values_2 = np.linspace(0,1000,2,retstep=True)
print (x_values_1)
print(x_values_2)

[  0.  50. 100.]
[ 0. 25. 50. 75.]
(array([   0., 1000.]), np.float64(1000.0))


# ***NUMPY'S SPECIAL VLAUES***

In [42]:
# Explanation
# np.nan
# Ek special floating-point value jo "missing or undefined data" represent karta hai — ye koi number nahi hai.
# Sabse dangerous property: np.nan == np.nan bhi False return karta hai — isliye check karne ke liye np.isnan() use karna padta hai.
# Example: agar tumhari dataset mein koi value missing ho — jaise ek student ka marks record nahi — wahan np.nan rakho, 0 nahi.

# --- SYNTAX / FORMULA ---
# np.nan                              --> sirf value hai, koi brackets nahi, direct use karo
# np.isnan( array )                   --> check karo kaunsi values nan hain
# np.nansum( array )                  --> sum karo, nan ignore karo
# np.nanmean( array )                 --> mean nikalo, nan ignore karo
# np.nanmax( array )                  --> max nikalo, nan ignore karo

# --- COMMON TRAPS ---
# np.nan + 5        -->  nan   (koi bhi math nan ke saath karo, answer nan aata hai)
# np.nan == np.nan  -->  False (ye bhool mat jaana)
# np.isnan(np.nan)  -->  True  (sahi tarika check karne ka)

# --- EXAMPLE ---
#import numpy as np
#arr = np.array([1, 2, np.nan, 4, 5])
#print(np.nansum(arr))    # 12.0  -- nan ko skip karke sum kiya
#print(np.isnan(arr))     # [False False True False False]
print (np.nan)
print (np.isnan(np.sqrt(-1))) # with np.isnan it says ture
       #  AND WITHOUT NP.ISNAN 
print (np.sqrt(-1))

nan
True
nan


C:\Users\ZOVARI LAPTOP\AppData\Local\Temp\ipykernel_14560\1318561821.py:25: RuntimeWarning: invalid value encountered in sqrt
  print (np.isnan(np.sqrt(-1))) # with np.isnan it says ture
C:\Users\ZOVARI LAPTOP\AppData\Local\Temp\ipykernel_14560\1318561821.py:27: RuntimeWarning: invalid value encountered in sqrt
  print (np.sqrt(-1))


In [52]:
# np.isinf()
# Ek NumPy function jo check karta hai ke koi value infinite hai ya nahi — positive ya negative dono.
# Ye tab hota hai jab tum kisi number ko zero se divide karo — result infinity ban jaata hai, aur isinf() us ko detect karta hai.
# Example: machine learning mein loss explode ho jaye aur inf ban jaye — np.isinf() se turant pakad lo.

# --- SYNTAX / FORMULA ---
# np.isinf( value or array )          --> True/False return karta hai, inf hai ya nahi
# np.isposinf( array )                --> sirf positive infinity check karo (+inf)
# np.isneginf( array )                --> sirf negative infinity check karo (-inf)
# np.isfinite( array )                --> ulta kaam -- True agar value NORMAL ho (nan aur inf dono ko False karta hai)

# --- COMMON TRAPS ---
# 1/0 in Python     -->  ZeroDivisionError  (Python crash karta hai)
# np.float64(1)/0   -->  inf                (NumPy crash nahi karta, inf deta hai)
# np.inf + 999      -->  inf                (inf ke saath koi bhi math karo, inf hi rahega)
# np.inf == np.inf  -->  True               (nan se alag hai -- inf khud se equal hota hai)
print(np.inf)



print (np.isinf(np.array([10]) / 0)) # With isinf function
         # AND WITHOUT IT
print (np.array([10]) / 0 )
 

inf
[ True]
[inf]


C:\Users\ZOVARI LAPTOP\AppData\Local\Temp\ipykernel_14560\1971135503.py:21: RuntimeWarning: divide by zero encountered in divide
  print (np.isinf(np.array([10]) / 0)) # With isinf function
C:\Users\ZOVARI LAPTOP\AppData\Local\Temp\ipykernel_14560\1971135503.py:23: RuntimeWarning: divide by zero encountered in divide
  print (np.array([10]) / 0 )


# **MATHEMATICAL OPERATIONS**

In [54]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]
a1 = np.array(l1)
a2 = np.array(l2)
# Explanation 
# In python the array is repeated 5 times and in NUMPY its multiplied as in the functiona
print (l1 * 5)
print (a1 * 5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [56]:
# addition
# In python it combines both lists and in Numpy it add like 1 + 6 the down element  
print (l1 + l2)
print (a1 + a2)

print (a1 - a2)


print (a1 * a2)

a3 = [1,2,3,4,5,6,7,8]

print (a1 / a3)
# IN Numpy it performs the function but in simple python it does't so that why we use NUMPY

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 7  9 11 13  5]


# **NP.EYE**

In [22]:
# np.eye
# np.eye may look same as the np.identity but there is one Difference between them and that is the "Indexing"
# IN np.identity the diagonals are fixed as one no other value but in np.eye we can change it by writing like this 
# np.eye(7,k= the diagonal you want like) in 7 the indexing start from 0 always as i selected 7 its 6 and one is 0 and in the code 1 so you can see its
# number 2 
# Formula = np.eye(index size,k=the start point of 1)
np.eye(7,k=-1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [26]:
arr_2= np.diag([1,2,3,4])
print (arr_2)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [56]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# **Problem 1:Run np.random.rand(3) twice without seed. Are the results same or different?**

# **Problem 2:Now set np.random.seed(0) before each run. Are results same or different?**

In [84]:
np.random.seed(0)
np.random.rand(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [88]:
np.random.seed(0)
np.random.rand(3)


#                           HENCE PROVED
#                       They are different without seed 



array([0.5488135 , 0.71518937, 0.60276338])

In [ ]:
arr_3 = np.array([5,15,25,35,45,55,65,75,85,95])
arr_3

# **Get every 3rd element**

In [94]:
arr_3[::3]

array([ 5, 35, 65, 95])

# **Reverse the array**

In [95]:
arr_3[::-1]

array([95, 85, 75, 65, 55, 45, 35, 25, 15,  5])

# **Get all elements greater than 50**

In [99]:
arr_3[(arr_3>50)]

array([55, 65, 75, 85, 95])

# **Get all even indexed elements**

In [102]:
arr_3[::2]
# didnt figure out so i checked the solution above 

array([ 5, 25, 45, 65, 85])

# **Get elements at index 0,4,8**

In [158]:
arr_3[[0,4,8]] # this is fancy indexing 

array([ 5, 45, 85])

# **Set seed to 99, create 3x3 random array**

In [138]:
np.random.seed(99)
np.random.rand(3,3)

array([[0.67227856, 0.4880784 , 0.82549517],
       [0.03144639, 0.80804996, 0.56561742],
       [0.2976225 , 0.04669572, 0.9906274 ]])

# **Create rand(3,3) and randn(3,3), compare min and max**

In [148]:
# didn't figured out so i checked the solution
r1 = np.random.rand(3,3)
print ("rand min:", r1.min(), "max:", r1.max())

rand min: 0.07674838391545857 max: 0.8068766138390322


In [150]:
r2 = np.random.randn(3,3)
print ("randn min:", r2.min(), "randn max:", r2.max())


randn min: -1.0868851531619907 randn max: 1.6447565674588234


# **Get all elements between 20 and 70**

In [151]:
arr_3[(arr_3>20) & (arr_3<70)]

array([25, 35, 45, 55, 65])

# **Reverse only the first 5 elements**

In [ ]:
arr_3[:5][::-1]
# however the question was not answered correctly, i m proud of my slef that on the 5th day i m able to do 6-8 questions by self and in this i was able to get the first five elements but didn't understand  how to reverse it 
# CLAUDE i m gona share this to you so rate me and give me explanations to those q that i cant solve 

# **Create a VIEW of first 5 elements, modify it, prove original changed**

In [171]:
arr = np.array([5,15,25,35,45,55,65,75,85,95])
view = arr[0:5]
view[2] = 99
arr
# PROVES IT, IT IS A VIEW 

array([ 5, 99, 25, 35, 45, 55, 65, 75, 85, 95])

# **Create a COPY of last 5 elements, modify it, prove original NOT changed**

In [175]:
import numpy as np

# Step 1: Pehle ek array banate hain
arr_4 = np.array([5,15,25,35,45,55,65,75,85,95])
#  index:          0   1   2   3   4   5   6   7   8   9

# Step 2: Last 5 elements select karte hain
# -5 matlab end se 5th element se shuru karo
copy = arr_4[-5:]
# copy = [55, 65, 75, 85, 95]
#  index:  0   1   2   3   4  ← copy ke APNE indices 0 se start hote hain

# Step 3: 95 ko 195 mein change karna tha
# JO GALTI MAIN KAR RAHA THA:
# Maine socha index 9 likhun kyunki 95 arr_4 mein index 9 pe hai
# LEKIN copy ke apne indices hain jo 0 se start hote hain
# copy mein sirf 5 elements hain → indices 0,1,2,3,4
# index 9 copy mein exist hi nahi karta → ERROR aata tha

# SAHI TARIKA:
# copy[4] = copy ka last element = 95
copy[4] = 195

print(copy)
# [55, 65, 75, 85, 195]

print(arr_4)
# [5, 15, 25, 35, 45, 55, 65, 75, 85, 195]
# arr_4 BHI change ho gaya kyunki copy ek VIEW hai
# agar original bachana ho to likho: arr_4[-5:].copy()

[  5  15  25  35  45  55  65  75  85 195]


# **Problem 11 — fancy indexing at index 2,5,7**

In [177]:
arr_5 = np.array([5,15,25,35,45,55,65,75,85,95])
arr_5[[2,5,7]]

array([25, 55, 75])

# **Prove fancy indexing is COPY:**

In [189]:
arr_6 = np.array([5,15,25,35,45,55,65,75,85,95])

fancy = arr_6[[1,2,3]]

fancy[2]= 199

print (arr_6)

[ 5 15 25 35 45 55 65 75 85 95]


# 