In [89]:

import numpy as np

#this is how we add arrays in numpy
# 1d array dwon below
a  = np.array([8,0,4])
c  = np.array([16,20,4])
b  = np.array([2,9,5])

print (a+b+c)

# 2D DIMENSION ARRAY

d = np.array([[7,6,3],[8,3,9]])
print (d)

# 3D DIMENSION ARRAY
# jab hum nay 2d array bani thi to us main hum phele np.array([[elements...],[elements]]) ik round bracket phir ik square bracket then in the second
# square bracket we wrote elements this is called 2d array in hinglish


# jab hum nay 3d array banaye gayn to hum phele np.array([[[elements],[elements]],[[elements],[elements],]]) 
# is main hum ik round bracket say shru karye gayn phir ik square bracket or phir ik or phir 3rd square bracket main  elements put karyn gay 
# phir comma put karye gayn or phir is kay baad 2 row of elements phir shuru ki bracket pe comma laga kay 2nd slice main do bracket put karyen gaye 
# or dosari bracket main elements put karye gay or phir comma or phir say elements ki row likhe gayn  or phir 3dimension array ban jiaye gi
h = np.array([
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ],
    [
        [11,12,13,14,15],
        [16,17,18,19,20]
    ]
])
print(h)
h.shape


[26 29 13]
[[7 6 3]
 [8 3 9]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


(2, 2, 5)

In [90]:
h.ndim

3

In [91]:
#Get Dimensions 
#Formula = variable.ndim
#Form above example 
# Abbrevation of ndim "Number of Dimensions"
a.ndim

1

In [92]:
# Hope so you understand how to get DIMENSIONS AND ADD ARRAYS (●'◡'●)😊
d.ndim

2

In [93]:
#This is how we gona get the shape 
#Formula = variable.shape
d.shape

(2, 3)

In [94]:
#Get(default) DATA Type
#Formula = variable.dtype
d.dtype

dtype('int64')

In [95]:
f = np.array([[7,6,3],[8,3,9]], dtype='int16')
print (f)

[[7 6 3]
 [8 3 9]]


In [96]:
#Get(modified or coustimized dtype to make the size samller.If you have smaller value you can change to int16,8= as int16=2bytes) DATA Type
#Formula = variable.dtype
f.dtype

dtype('int16')

In [97]:
# Get Size 
# Formula = variable.itemsize
# itemsize returns the number of bytes used by one element of the array.
g = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]], dtype='int16')
g.itemsize

2

In [98]:
# To find out Total no. of elements in a array 
# Formula = variable.size 
g.size
#Ans: as you can see below answer is 16 and there are 16 elements in the g array                     

16

In [99]:
# Get nbytes 
# To find the Total Size of the all the elements in the array
# Formula = variable.nbytes 
# Mathematical RelationShip:
# number of elements * size of each element 
g.nbytes

32

In [100]:
h.nbytes 

160

In [101]:
h.dtype

dtype('int64')

In [102]:
float_arr = np.array([[1.0,2.0,3.0,4.0],[5.0,6.0,7.0,8.0]])

float_arr.dtype

dtype('float64')

In [103]:
float_arr.itemsize

8

In [104]:
float_arr.nbytes

64

In [2]:
# PYTHON VS NUMPY TIME COMPARISON
import time
import numpy as np
# Python loop
start = time.time()
total = sum([i for i in range(1000000)])
print("Python loop:", time.time() - start)

# NumPy
start = time.time()
total = np.sum(np.arange(1000000))
print("NumPy:", time.time() - start)

Python loop: 0.11774826049804688
NumPy: 0.057318925857543945


In [ ]:
Links with more information! 

NumPy vs Lists:
https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

Indexing: 
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

Array Creation Routines:
https://numpy.org/doc/stable/reference/routines.array-creation.html

Math Routines Docs:
https://numpy.org/doc/stable/reference/routines.math.html

Linear Algebra Docs:
https://numpy.org/doc/stable/reference/routines.linalg.html