In [42]:

import numpy as np

#this is how we add arrays in numpy
# 1d array dwon below
a  = np.array([8,0,4])
c  = np.array([16,20,4])
b  = np.array([2,9,5])

print (a+b+c)

# 2D DIMENSION ARRAY

d = np.array([[7,6,3],[8,3,9]])
print (d)

[26 29 13]
[[7 6 3]
 [8 3 9]]


In [43]:
#Get Dimensions 
#Formula = variable.ndim
#Form above example 
# Abbrevation of ndim "Number of Dimensions"
a.ndim

1

In [71]:
# Hope so you understand how to get DIMENSIONS AND ADD ARRAYS (●'◡'●)😊
d.ndim

2

In [66]:
#This is how we gona get the shape 
#Formula = variable.shape
d.shape

(2, 3)

In [46]:
#Get(default) DATA Type
#Formula = variable.dtype
d.dtype

dtype('int64')

In [69]:
f = np.array([[7,6,3],[8,3,9]], dtype='int16')
print (f)

[[7 6 3]
 [8 3 9]]


In [70]:
#Get(modified or coustimized dtype to make the size samller.If you have smaller value you can change to int16,8= as int16=2bytes) DATA Type
#Formula = variable.dtype
f.dtype

dtype('int16')

In [55]:
# Get Size 
# Formula = variable.itemsize
# itemsize returns the number of bytes used by one element of the array.
g = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]], dtype='int16')
g.itemsize

2

In [60]:
# To find out Total no. of elements in a array 
# Formula = variable.size 
g.size
#Ans: as you can see below answer is 16 and there are 16 elements in the g array                     

16

In [62]:
# Get nbytes 
# To find the Total Size of the all the elements in the array
# Formula = variable.nbytes 
# Mathematical RelationShip:
# number of elements * size of each element 
g.nbytes

32